name: CI/CD Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set PYTHONPATH as environment variable for the job
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/app:$PYTHONPATH" >> $GITHUB_ENV
      # Run unit tests
      - name: Run unit tests
        run: |
          pytest app/test/unit

      # Run integration tests
      #      - name: Run integration tests
      #        run: |
      #          pytest app/test/integration
      # Run SonarCloud Analysis
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v5.0.0
        with:
          args: >
            -Dsonar.organization=your-org
            -Dsonar.projectKey=your-project-key
            -Dsonar.projectName=your-project-name
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
