name: CI/CD Workflow

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

        # Set PYTHONPATH so that the app module can be found
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/app" >> $GITHUB_ENV

        # Verify PYTHONPATH
      - name: Verify PYTHONPATH
        run: echo $PYTHONPATH # Confirm that PYTHONPATH is correctly set

      # Run unit tests
      - name: Run unit tests
        run: |
          PYTHONPATH=$(pwd)/app pytest app/test/unit

      # Run integration tests
      - name: Run integration tests
        run: |
          PYTHONPATH=$(pwd)/app pytest app/test/integration

      # Run static analysis (SonarCloud)
      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=your-org
            -Dsonar.projectKey=your-project-key
            -Dsonar.projectName=your-project-name
